OnePieceBounties/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from bounties import urls as bounties_urls

urlpatterns = [
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^onepiecebounties/', include(bounties_urls, namespace='bounties')),
    url(r'^admin/', include(admin.site.urls)),
] 

bounties/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pirate_id>\d+)/$', views.get_pirate, name='get_pirate'),
]

bounties/models.py
from django.db import models
from django.template.defaultfilters import slugify

class Crew(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

class Pirate(models.Model):
    DEAD_OR_ALIVE = 1
    ONLY_ALIVE = 2
    
    STATUS_CHOICES = (
        (DEAD_OR_ALIVE, 'Dead or Alive'),
        (ONLY_ALIVE, 'Only Alive'),
    )
    
    name = models.CharField(max_length=128)
    bounty = models.IntegerField(null=True)
    crew = models.ForeignKey(Crew, on_delete=models.SET_NULL, blank=True, null=True)
    wanted_status = models.IntegerField(choices=STATUS_CHOICES, default=DEAD_OR_ALIVE, null=True)

    def filename(self):
        return slugify(self.name)

    def formatted_bounty(self):
        return '{:,}'.format(self.bounty) if self.bounty else None

    def __str__(self):
        return self.name

bounties/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Pirate

# TODO: refactor. Tries to do too many things in one method
def index(request):
    pirates = Pirate.objects.all()
    keyword = request.GET.get('pirate-search-field')
    
    if keyword:
        results = Pirate.objects.filter(name__icontains=keyword)

        if results.count() == 1:
            return redirect('/onepiecebounties/%d/' % (results.first().id,))
        elif results.count() > 1:
            return render(request, 'list.html', {'pirates': results})
        
    return render(request, 'index.html', {'pirates' : pirates})

def get_pirate(request, pirate_id):
    pirates = Pirate.objects.all()
    pirate = Pirate.objects.get(id=pirate_id)
    return render(request, 'profile.html', {'pirate': pirate, 'pirates': pirates})

bounties/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<!-- Template structure from https://oncampus.oberlin.edu/webteam/2012/09/architecture-django-templates -->
	{% block meta_tags %}
		  <meta name="viewport" content="width=device-width, initial-scale=1">
	{% endblock %}
	<title>
		{% block title %}
			WANTED | Unofficial list of bounties in One Piece
		{% endblock %}
	</title>
	{% block css %}
		<link rel="stylesheet" href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" />
		<link rel="stylesheet" href="{% static "css/fonts.css" %}" />
		<link rel="stylesheet" href="{% static "css/style.css" %}" />
	{% endblock %}
	{% block javascript %}{% endblock %}
</head>
<body>
	<main role="main">
		{% block content %}{% endblock %}
	</main>

	{% block javascript_onload %}{% endblock %}
</body>
</html>

bounties/templates/header.html
		<header class="text-center">
			<a href="{% url 'bounties:index' %}">
				<h1>WANTED</h1>
			</a>
		</header>

bounties/templates/index.html
{% extends "base.html" %}

{% load staticfiles %}

{% block css %}
	{{ block.super }}
	<link rel="stylesheet" href="{% static "css/index-search.css" %}" />
{% endblock %}

{% block content %}
	{% include "header.html" %}

	<div class="container">
		<div class="row">
			<div class="col-md-offset-2 col-xs-offset-1 col-md-8 col-xs-10">
				{% include "search.html" %}
			</div>
		</div>
	</div>
{% endblock %}

bounties/templates/list.html
{% extends "base.html" %}

{% load humanize %}
{% load staticfiles %}

{% block css %}
	{{ block.super }}
	<link rel="stylesheet" href="{% static "css/default-search.css" %}" />
{% endblock %}

{% block content %}

	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-form navbar-left">
				{% include "search.html" %}
			</div>
		</div>
	</nav>

	<div class="container">
		{% include "header.html" %}

		<div class="row text-center">
			{% for pirate in pirates %}
				<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-offset-0 col-md-6 col-lg-4 pirate-detail">
					<a href="{% url 'bounties:get_pirate' pirate.id %}">
						<img src="/static/images/pirates/{{ pirate.filename }}.jpg" class="poster thumbnail" />
						<div class="detail-text grid">
							<p class="wanted-status">
								{% if pirate.wanted_status %}
									{{ pirate.get_wanted_status_display|upper }}
								{% endif %}
							</p>
							<p class="name">
								{{ pirate.name|upper }}
							</p>
							<p class="crew">{{ pirate.crew.name|upper }}</p>
						</div>
					</a>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock content %}

bounties/templates/page.html
{% extends 'base.html'}

{% block content %}

bounties/templates/profile.html
{% extends "base.html" %}

{% load humanize %}
{% load staticfiles %}

{% block css %}
	{{ block.super }}
	<link rel="stylesheet" href="{% static "css/default-search.css" %}" />
{% endblock %}

{% block content %}
	<nav class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-form navbar-left">
				{% include "search.html" %}
			</div>
		</div>
	</nav>
	<div class="container">
		{% include "header.html" %}
		<div class="row">
			<div class="col-lg-offset-2 col-sm-offset-1 col-lg-8 col-sm-10 text-center pirate-detail">
				<img src="/static/images/pirates/{{ pirate.filename }}.jpg" class="poster" />
				<div class="detail-text solo">
					<h2 class="wanted-status">
						{% if pirate.wanted_status %}
							{{ pirate.get_wanted_status_display|upper }}
						{% endif %}
					</h2>
					<h3 class="name">{{ pirate.name|upper }}</h3>
					{% if pirate.bounty %}
						<span class="bounty">{{ pirate.bounty|intcomma }}</span>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

		

bounties/templates/search.html
			<form method="GET" action="/onepiecebounties/" class="search-panel">
				<div class="form-group">
					<div class="input-group">
					    <span class="input-group-addon">
					    	<i class="glyphicon glyphicon-search"></i>
					    </span>
						<input type="search" placeholder="Search for a pirate..." name="pirate-search-field" list="pirate-names" class="form-control"/>
						<datalist id="pirate-names">
							{% for pirate in pirates %}
								<option value="{{ pirate.name }}">{{ pirate.name }}</option>
							{% endfor %}
						</datalist>
					</div>
				</div>
			</form>